# Generated by Django 3.2.8 on 2021-10-16 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAppExample', '0003_auto_20211015_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
